// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using US_5A_Net;

namespace US_5A_Net.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20221119102908_MigBD")]
    partial class MigBD
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("US_5A_Net.models.Flights", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("countCrew")
                        .HasColumnType("int");

                    b.Property<int>("countPas")
                        .HasColumnType("int");

                    b.Property<DateTime>("eta")
                        .HasColumnType("datetime2");

                    b.Property<int>("numflight")
                        .HasColumnType("int");

                    b.Property<double>("priceCrew")
                        .HasColumnType("float");

                    b.Property<double>("pricePas")
                        .HasColumnType("float");

                    b.Property<double>("procDop")
                        .HasColumnType("float");

                    b.Property<double>("sum")
                        .HasColumnType("float");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("FlightersBD");
                });
#pragma warning restore 612, 618
        }
    }
}
